version: '3.7'

services:
  arcgis-prometheus:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      USERNAME:
      PASSWORD:
      SERVER_URL:
      PORT:
    networks:
      monitoring-net:
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}/healthcheck
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-3s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}

networks:
  monitoring-net:
    name: ${MONITORING_NET_NAME:-monitoring-net}
    driver: ${MONITORING_NET_DRIVER:-overlay}
    attachable: ${MONITORING_NET_ATTACHABLE:-true}
